spring:
  application:
    name: customer-app

bxframework:
  tenant-id: DEFAULT
  request:
    system-header: "bxmc.core.ext.context.DefaultSystemHeader"
  base-package: "sample,sample.poc.customer.controller,sample.poc.customer.service,sample.poc.customer.dbio,sample.poc.customer.component"
  application:
    type : online
    datasource:
      main-ds: # Datasource name
        jdbc: # JdbcApplicationDataSource
          driver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:mem:test;MODE=Oracle
          username: sa
          password:
---
spring:
  profiles: local | test
  main:
    banner-mode: "off"
  cloud:
    kubernetes:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            local-service:
              - uri: http://localhost:${server.port}
  zipkin:
    enabled: false

bxframework:
  etcd:
    enabled: false
  request:
    control-skip-patterns:
      - "/**"
logging:
  level:
    io.fabric8.kubernetes.client.Config: error
    org.apache: debug #${logging.level.root}
    bxmc: trace
    bxmc.request.mapping.AnnotatedRequestMappingHandlerMapping: debug #${logging.level.root}
    org.springframework.web: debug
